# Generated by Django 5.0.1 on 2024-04-17 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresso_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('vagas', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='ingresso',
            old_name='lugar',
            new_name='vaga',
        ),
        migrations.AddField(
            model_name='ingresso',
            name='estadio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estadio', to='ingresso_app.estadio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='ingresso_app.usuario'),
        ),
    ]
